apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - image: ghcr.io/robotjoosen/${APP_NAME}:${VERSION_TAG}
          name: app
          volumeMounts:
            - name: shared-files
              mountPath: /var/shared/
        - image: nginx:alpine
          name: nginx
          volumeMounts:
            - name: shared-files
              mountPath: /var/shared/
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: shared-files
          emptyDir: {}
        - name: nginx-config-volume
          configMap:
            name: ${APP_NAME}-settings
